# Generated by Django 2.2.1 on 2021-03-24 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pip_attr_provider', '0002_auto_20210323_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='user_starter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_starter', to=settings.AUTH_USER_MODEL),
        ),
    ]
