# Generated by Django 2.2.1 on 2021-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pip_attr_provider', '0003_encounter_user_starter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'patient'), (2, 'ambulance'), (3, 'call_centre'), (4, 'hospital'), (5, 'org_admin')], default=1, null=True)),
                ('identifier', models.IntegerField(null=True, unique=True)),
                ('shift_start', models.DateTimeField(null=True)),
                ('shift_end', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
