# Generated by Django 2.2.1 on 2021-03-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pip_attr_provider', '0005_auto_20210329_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pip_attr_provider.Users'),
        ),
    ]
